### ISSUE TITLE
Add interruption level option

### ISSUE THREAD

**Issue by kaiserkiwi** [crnh/home-assistant-blueprints#1]
Hi there. Great blueprint. 
I have a feature request. 

iOS and macOS devices have different levels of interruption for notifications. So it's possible to get the notification through despite I have everything disabled. With the strong implementation of focus modes in iOS and macOS this is a feature that is quite nice.

Most notifications are not extremely important, so the `active` level (default) is absolutely fine. This respects the users settings for the whole app. But there are three different modes according to the official documentation (https://companion.home-assistant.io/docs/notifications/notifications-basic/#interruption-level)

- `passive` – This one is completely silent and just is there when you unlock the phone (great for battery low messages or something that can definitely wait)
- `active` – The default as stated above (great for most notfications)
- `time-sensitive` – This one breaks the focus even if Home Assistant is muted in this focus. (Great for close doorbells and stuff like that)
- `critical` – This one breaks through everything, even mute. This is the highest level. (Great for leak sensors, security stuff or smoke alarm)

It would be nice if I could add this as a simple parameter for each notification I want to send.

**Comment by crnh** [comment]
Hi, thanks for your suggestion and nice to see people are using this blueprint!
This is not too hard to implement, but did you already try passing this parameter to your notifications using the `data` parameter? If so, why is that solution not sufficient?
Example:

```yaml
service: script.notify_everybody_home
data:
  message: Test message
  title: Example title
  data:
    push:
      interruption-level: passive
```

**Comment by kaiserkiwi** [comment]
My bad. I just didn't realize that this options exists. I still think it would be nice to have a dropdown for this, but I think it's not as urgent as I thought 😅
